### ISSUE TITLE
Query: Eco mode sysfs path

### ISSUE THREAD

**Issue by maniacx** [chantk/panasonic-laptop#2]
Not an issue but a question.
I am made a Gnome extension so change battery threshold and want to add panasonic device.
But i cannot figure out what is the sysfs path to turn on eco mode on or off?
Is it 
`/sys/devices/platform/panasonic/eco_mode`
or 
`/sys/devices/platform/panasonic-laptop/eco_mode`

Also Want to comfirm if eco_mode set to  '1' sets battery threshold to 80%? or is it some other value?

**Comment by chantk** [comment]
Hi maniacx,

On Wed, 22 Mar 2023 at 17:51, maniacx ***@***.***> wrote:

> Not an issue but a question.
> I am made a Gnome extension so change battery threshold and want to add
> panasonic device.
> But i cannot figure out what is the sysfs path to turn on eco mode on or
> off?
> Is it
> /sys/devices/platform/panasonic/eco_mode
> or
> /sys/devices/platform/panasonic-laptop/eco_mode
>

It's /sys/devices/platform/panasonic/eco_mode.


> Also Want to comfirm if eco_mode set to '1' sets battery threshold to 80%?
> or is it some other value?
>

Correct. ECO mode is Panasonic's term of battery threshold.
1 means eco_mode on, which means limiting battery threshold to 80%.
0 means eco_mode off, charging up to 100%.

One thing worth noting is the current driver only supports up to the CF-W5,
Y7, R6 series (rather ancient models). Thanks to Sofia Lee <
***@***.*** ***@***.***>> who recently contributed
quite a few recent models' DSDTs. I'm hoping to bring the driver more
up-to-date.

--
Kenneth

**Comment by maniacx** [comment]
Ok. Thank you for the information. I will add it to my extension the next update.
